language: python 
python:
  - "3.5"

os: linux
sudo: required
dist: trusty

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gnat-4.8 zlib1g-dev
  - sudo apt-get install -y llvm-3.5-dev llvm-3.5-tools libedit-dev

before_script:
  - pip install -e .
  - git clone https://github.com/vunit/vunit.git
  - cd vunit
  - git checkout d9746b40949d7b89c90805e2ed3be67b33d635b5
  - git submodule update --init --recursive
  - pip install -e .
  - cd ..
  - git clone --depth 1 https://github.com/tgingold/ghdl.git ghdl
  - cd ghdl
  - mkdir build-llvm
  - cd build-llvm
  - ../configure --prefix=../../install-ghdl-llvm/ --with-llvm-config=llvm-config-3.5
  - make
  - make install
  - cd ../../
  - export PATH=$PATH:`pwd`/install-ghdl-llvm/bin/

script: python tests/test_binary_tree.py